name: Run tests on pull requests to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bash 3.2.57
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential
          wget https://ftp.gnu.org/gnu/bash/bash-3.2.57.tar.gz
          tar xzf bash-3.2.57.tar.gz
          cd bash-3.2.57
          ./configure
          make -j4
          sudo make install
        shell: bash

      - name: Check Bash version
        run: /usr/local/bin/bash --version
        shell: bash

      - name: Build
        run: make

      - name: Run unit tests
        run: make unit_test

      - name: Run E2E tests
        run: make e2e_test
